before_script: npm install jasmine-node

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode

matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: ree
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
