{Node, Class, Module, ClassMethod, InstanceMethod, Constant, Variable} = require 'dock/nodes'

class exports.Base
  constructor: (@filename, @contents) ->
    
  class:           (args...) -> new Class          args...
  module:          (args...) -> new Module         args...
  class_method:    (args...) -> new ClassMethod    args...
  instance_method: (args...) -> new InstanceMethod args...
  constant:        (args...) -> new Constant       args...
  variable:        (args...) -> new Variable       args...
  
  document: ->
    unless @root
      @root = new Node 'Root'
      @generate()
    @root
